create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(12,2) not null,
  badge text default 'PROMOÇÃO',
  image_url text not null,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamp with time zone not null default now()
);

insert into public.categories (name, slug, sort_order)
values
  ('PC Gamer', 'gamer', 1),
  ('PC Escritório', 'office', 2),
  ('Kits', 'kit', 3),
  ('Monitores', 'monitor', 4),
  ('Nobreak', 'nobreak', 5)
on conflict (slug) do nothing;

insert into public.products (category_id, name, slug, description, price, badge, image_url, featured, active)
select c.id, p.name, p.slug, p.description, p.price, p.badge, p.image_url, p.featured, true
from (
  values
    ('gamer', 'PC Gamer Ryzen 5', 'pc-gamer-ryzen-5', '16GB • SSD 512GB • RTX 3060', 4999.00, 'PROMOÇÃO', 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7', true),
    ('gamer', 'PC Gamer Intel i5', 'pc-gamer-intel-i5', '16GB • SSD 1TB • RTX 4060', 6499.00, 'PROMOÇÃO', 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5', true),
    ('office', 'PC Escritório i3', 'pc-escritorio-i3', '8GB • SSD 256GB', 2199.00, 'PROMOÇÃO', 'https://http2.mlstatic.com/D_NQ_NP_2X_881943-MLA94688664499_102025-F.webp', false),
    ('kit', 'Kit PC Completo', 'kit-pc-completo', 'PC + Monitor + Teclado + Mouse', 2799.00, 'PROMOÇÃO', 'https://http2.mlstatic.com/D_NQ_NP_2X_612413-MLA99563555920_122025-F.webp', false),
    ('monitor', 'Monitor Hayom 19"', 'monitor-hayom-19', 'HD • HDMI/VGA', 399.00, 'PROMOÇÃO', 'https://http2.mlstatic.com/D_NQ_NP_2X_852841-MLA99952832883_112025-F.webp', false),
    ('monitor', 'Monitor Hayom 21.5"', 'monitor-hayom-21-5', 'Full HD • HDMI', 549.00, 'PROMOÇÃO', 'https://m.media-amazon.com/images/I/61WB948IEGL._AC_SX679_.jpg', false),
    ('monitor', 'Monitor Brazil PC 19"', 'monitor-brazil-pc-19', 'HD • HDMI/VGA', 379.00, 'PROMOÇÃO', 'https://images.tcdn.com.br/img/img_prod/1165337/monitor_brazil_pc_19_hd_led_widescreen_hdmi_vga_ajuste_de_angulo_bpc_19we02_b_20539_4_6cd0190bc501370580a6ab141cff8f3c.jpg', false),
    ('monitor', 'Monitor Brazil PC 21.5"', 'monitor-brazil-pc-21-5', 'Full HD • HDMI', 529.00, 'PROMOÇÃO', 'https://images.kabum.com.br/produtos/fotos/sync_mirakl/386383/Monitor-Fox-Racer-21-5-Polegadas-1600x900-75Hz-HDMI-VGA-Widescreen_1666894718_gg.jpg', false),
    ('monitor', 'Monitor Duex 23.8"', 'monitor-duex-23-8', 'Full HD • HDMI', 649.00, 'PROMOÇÃO', 'https://http2.mlstatic.com/D_NQ_NP_2X_873565-MLU79050099107_092024-F.webp', false),
    ('nobreak', 'Nobreak Intelbras 600VA', 'nobreak-intelbras-600va', 'Bivolt', 449.00, 'PROMOÇÃO', 'http://backend.intelbras.com/sites/default/files/2021-06/nobreak_attiv_600_perp_esq.png', false),
    ('nobreak', 'Nobreak Intelbras 1200VA', 'nobreak-intelbras-1200va', 'Bivolt', 799.00, 'PROMOÇÃO', 'http://backend.intelbras.com/sites/default/files/2021-06/nobreak_attiv_600_perp_esq.png', false),
    ('nobreak', 'Nobreak Intelbras 1500VA', 'nobreak-intelbras-1500va', 'Bivolt', 1099.00, 'PROMOÇÃO', 'http://backend.intelbras.com/sites/default/files/2021-06/nobreak_attiv_600_perp_esq.png', false)
) as p(category_slug, name, slug, description, price, badge, image_url, featured)
join public.categories c on c.slug = p.category_slug
on conflict (slug) do nothing;
